### ISSUE TITLE
not compatible with godaddy wordpress hosting...

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-file-page-cache#2] opened 2018-05-12 08:59 UTC
i tried you plugin on several plateform i have website on, from contabo to vultr and everything is okay...

but as soon that i activated this plugin on godaddy plateform even if not activated...

like no option touch or hit it turn in error 500.

i had to go in the database and desactivate all plugin to regain access to the wordpress in question...

so maybe if you can explore futher what is the problem with the godaddy plateform, like it's php 5.6 mysql, opcache or not enable should not be a problem only if we activated the option and it should give a nag like no opcache activated or found or i don't know.

because zend opcache is activate.

**Comment by optimalisatie** [comment] 2018-05-20 09:12
Hi Maxime,

Would it be possible to provide the corresponding PHP error log entry?

**Comment by mxmkmarquette** [comment] 2018-05-20 17:26
[20-May-2018 17:08:40 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:08:43 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:08:49 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:08:49 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:08:53 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:08:57 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:09:08 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:09:10 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:09:18 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:09:21 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:09:29 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188
[20-May-2018 17:09:31 UTC] PHP Parse error:  syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/content/p3pnexwpnas15_data01/38/3575438/html/wp-content/plugins/wordpress-file-page-cache-0.0.4/controllers/filecache.class.php on line 188

**Comment by mxmkmarquette** [comment] 2018-05-20 17:27
and what i got is error 500 and not able to reach my website i need to desactivate all the plugin via database in that case.

**Comment by optimalisatie** [comment] 2018-05-21 07:44
Hi Maxime,

Thanks again for providing feedback! The issue has been resolved in `v0.0.10`.

The issue was caused by a PHP class method named [print](http://php.net/manual/en/function.print.php) which is not allowed because it is a language construct and not a function.

**Closed by optimalisatie** 2018-05-21 07:44 UTC
